/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AccountsResponseData {
  #[serde(rename = "accounts")]
  accounts: Vec<::models::Account>,
  /// The knowledge of the server
  #[serde(rename = "server_knowledge")]
  server_knowledge: i64
}

impl AccountsResponseData {
  pub fn new(accounts: Vec<::models::Account>, server_knowledge: i64) -> AccountsResponseData {
    AccountsResponseData {
      accounts: accounts,
      server_knowledge: server_knowledge
    }
  }

  pub fn set_accounts(&mut self, accounts: Vec<::models::Account>) {
    self.accounts = accounts;
  }

  pub fn with_accounts(mut self, accounts: Vec<::models::Account>) -> AccountsResponseData {
    self.accounts = accounts;
    self
  }

  pub fn accounts(&self) -> &Vec<::models::Account> {
    &self.accounts
  }


  pub fn set_server_knowledge(&mut self, server_knowledge: i64) {
    self.server_knowledge = server_knowledge;
  }

  pub fn with_server_knowledge(mut self, server_knowledge: i64) -> AccountsResponseData {
    self.server_knowledge = server_knowledge;
    self
  }

  pub fn server_knowledge(&self) -> &i64 {
    &self.server_knowledge
  }


}



