/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Category {
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "category_group_id")]
  category_group_id: String,
  #[serde(rename = "name")]
  name: String,
  /// Whether or not the category is hidden
  #[serde(rename = "hidden")]
  hidden: bool,
  /// If category is hidden this is the id of the category group it originally belonged to before it was hidden.
  #[serde(rename = "original_category_group_id")]
  original_category_group_id: Option<String>,
  #[serde(rename = "note")]
  note: Option<String>,
  /// Budgeted amount in milliunits format
  #[serde(rename = "budgeted")]
  budgeted: i64,
  /// Activity amount in milliunits format
  #[serde(rename = "activity")]
  activity: i64,
  /// Balance in milliunits format
  #[serde(rename = "balance")]
  balance: i64,
  /// The type of goal, if the category has a goal (TB='Target Category Balance', TBD='Target Category Balance by Date', MF='Monthly Funding', NEED='Plan Your Spending')
  #[serde(rename = "goal_type")]
  goal_type: Option<String>,
  /// The month a goal was created
  #[serde(rename = "goal_creation_month")]
  goal_creation_month: Option<String>,
  /// The goal target amount in milliunits
  #[serde(rename = "goal_target")]
  goal_target: Option<i64>,
  /// The original target month for the goal to be completed.  Only some goal types specify this date.
  #[serde(rename = "goal_target_month")]
  goal_target_month: Option<String>,
  /// The percentage completion of the goal
  #[serde(rename = "goal_percentage_complete")]
  goal_percentage_complete: Option<i32>,
  /// The number of months, including the current month, left in the current goal period.
  #[serde(rename = "goal_months_to_budget")]
  goal_months_to_budget: Option<i32>,
  /// The amount of funding still needed in the current month to stay on track towards completing the goal within the current goal period.  This amount will generally correspond to the 'Underfunded' amount in the web and mobile clients except when viewing a category with a Needed for Spending Goal in a future month.  The web and mobile clients will ignore any funding from a prior goal period when viewing category with a Needed for Spending Goal in a future month.
  #[serde(rename = "goal_under_funded")]
  goal_under_funded: Option<i64>,
  /// The total amount funded towards the goal within the current goal period.
  #[serde(rename = "goal_overall_funded")]
  goal_overall_funded: Option<i64>,
  /// The amount of funding still needed to complete the goal within the current goal period.
  #[serde(rename = "goal_overall_left")]
  goal_overall_left: Option<i64>,
  /// Whether or not the category has been deleted.  Deleted categories will only be included in delta requests.
  #[serde(rename = "deleted")]
  deleted: bool
}

impl Category {
  pub fn new(id: String, category_group_id: String, name: String, hidden: bool, budgeted: i64, activity: i64, balance: i64, deleted: bool) -> Category {
    Category {
      id: id,
      category_group_id: category_group_id,
      name: name,
      hidden: hidden,
      original_category_group_id: None,
      note: None,
      budgeted: budgeted,
      activity: activity,
      balance: balance,
      goal_type: None,
      goal_creation_month: None,
      goal_target: None,
      goal_target_month: None,
      goal_percentage_complete: None,
      goal_months_to_budget: None,
      goal_under_funded: None,
      goal_overall_funded: None,
      goal_overall_left: None,
      deleted: deleted
    }
  }

  pub fn set_id(&mut self, id: String) {
    self.id = id;
  }

  pub fn with_id(mut self, id: String) -> Category {
    self.id = id;
    self
  }

  pub fn id(&self) -> &String {
    &self.id
  }


  pub fn set_category_group_id(&mut self, category_group_id: String) {
    self.category_group_id = category_group_id;
  }

  pub fn with_category_group_id(mut self, category_group_id: String) -> Category {
    self.category_group_id = category_group_id;
    self
  }

  pub fn category_group_id(&self) -> &String {
    &self.category_group_id
  }


  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> Category {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


  pub fn set_hidden(&mut self, hidden: bool) {
    self.hidden = hidden;
  }

  pub fn with_hidden(mut self, hidden: bool) -> Category {
    self.hidden = hidden;
    self
  }

  pub fn hidden(&self) -> &bool {
    &self.hidden
  }


  pub fn set_original_category_group_id(&mut self, original_category_group_id: String) {
    self.original_category_group_id = Some(original_category_group_id);
  }

  pub fn with_original_category_group_id(mut self, original_category_group_id: String) -> Category {
    self.original_category_group_id = Some(original_category_group_id);
    self
  }

  pub fn original_category_group_id(&self) -> Option<&String> {
    self.original_category_group_id.as_ref()
  }

  pub fn reset_original_category_group_id(&mut self) {
    self.original_category_group_id = None;
  }

  pub fn set_note(&mut self, note: String) {
    self.note = Some(note);
  }

  pub fn with_note(mut self, note: String) -> Category {
    self.note = Some(note);
    self
  }

  pub fn note(&self) -> Option<&String> {
    self.note.as_ref()
  }

  pub fn reset_note(&mut self) {
    self.note = None;
  }

  pub fn set_budgeted(&mut self, budgeted: i64) {
    self.budgeted = budgeted;
  }

  pub fn with_budgeted(mut self, budgeted: i64) -> Category {
    self.budgeted = budgeted;
    self
  }

  pub fn budgeted(&self) -> &i64 {
    &self.budgeted
  }


  pub fn set_activity(&mut self, activity: i64) {
    self.activity = activity;
  }

  pub fn with_activity(mut self, activity: i64) -> Category {
    self.activity = activity;
    self
  }

  pub fn activity(&self) -> &i64 {
    &self.activity
  }


  pub fn set_balance(&mut self, balance: i64) {
    self.balance = balance;
  }

  pub fn with_balance(mut self, balance: i64) -> Category {
    self.balance = balance;
    self
  }

  pub fn balance(&self) -> &i64 {
    &self.balance
  }


  pub fn set_goal_type(&mut self, goal_type: String) {
    self.goal_type = Some(goal_type);
  }

  pub fn with_goal_type(mut self, goal_type: String) -> Category {
    self.goal_type = Some(goal_type);
    self
  }

  pub fn goal_type(&self) -> Option<&String> {
    self.goal_type.as_ref()
  }

  pub fn reset_goal_type(&mut self) {
    self.goal_type = None;
  }

  pub fn set_goal_creation_month(&mut self, goal_creation_month: String) {
    self.goal_creation_month = Some(goal_creation_month);
  }

  pub fn with_goal_creation_month(mut self, goal_creation_month: String) -> Category {
    self.goal_creation_month = Some(goal_creation_month);
    self
  }

  pub fn goal_creation_month(&self) -> Option<&String> {
    self.goal_creation_month.as_ref()
  }

  pub fn reset_goal_creation_month(&mut self) {
    self.goal_creation_month = None;
  }

  pub fn set_goal_target(&mut self, goal_target: i64) {
    self.goal_target = Some(goal_target);
  }

  pub fn with_goal_target(mut self, goal_target: i64) -> Category {
    self.goal_target = Some(goal_target);
    self
  }

  pub fn goal_target(&self) -> Option<&i64> {
    self.goal_target.as_ref()
  }

  pub fn reset_goal_target(&mut self) {
    self.goal_target = None;
  }

  pub fn set_goal_target_month(&mut self, goal_target_month: String) {
    self.goal_target_month = Some(goal_target_month);
  }

  pub fn with_goal_target_month(mut self, goal_target_month: String) -> Category {
    self.goal_target_month = Some(goal_target_month);
    self
  }

  pub fn goal_target_month(&self) -> Option<&String> {
    self.goal_target_month.as_ref()
  }

  pub fn reset_goal_target_month(&mut self) {
    self.goal_target_month = None;
  }

  pub fn set_goal_percentage_complete(&mut self, goal_percentage_complete: i32) {
    self.goal_percentage_complete = Some(goal_percentage_complete);
  }

  pub fn with_goal_percentage_complete(mut self, goal_percentage_complete: i32) -> Category {
    self.goal_percentage_complete = Some(goal_percentage_complete);
    self
  }

  pub fn goal_percentage_complete(&self) -> Option<&i32> {
    self.goal_percentage_complete.as_ref()
  }

  pub fn reset_goal_percentage_complete(&mut self) {
    self.goal_percentage_complete = None;
  }

  pub fn set_goal_months_to_budget(&mut self, goal_months_to_budget: i32) {
    self.goal_months_to_budget = Some(goal_months_to_budget);
  }

  pub fn with_goal_months_to_budget(mut self, goal_months_to_budget: i32) -> Category {
    self.goal_months_to_budget = Some(goal_months_to_budget);
    self
  }

  pub fn goal_months_to_budget(&self) -> Option<&i32> {
    self.goal_months_to_budget.as_ref()
  }

  pub fn reset_goal_months_to_budget(&mut self) {
    self.goal_months_to_budget = None;
  }

  pub fn set_goal_under_funded(&mut self, goal_under_funded: i64) {
    self.goal_under_funded = Some(goal_under_funded);
  }

  pub fn with_goal_under_funded(mut self, goal_under_funded: i64) -> Category {
    self.goal_under_funded = Some(goal_under_funded);
    self
  }

  pub fn goal_under_funded(&self) -> Option<&i64> {
    self.goal_under_funded.as_ref()
  }

  pub fn reset_goal_under_funded(&mut self) {
    self.goal_under_funded = None;
  }

  pub fn set_goal_overall_funded(&mut self, goal_overall_funded: i64) {
    self.goal_overall_funded = Some(goal_overall_funded);
  }

  pub fn with_goal_overall_funded(mut self, goal_overall_funded: i64) -> Category {
    self.goal_overall_funded = Some(goal_overall_funded);
    self
  }

  pub fn goal_overall_funded(&self) -> Option<&i64> {
    self.goal_overall_funded.as_ref()
  }

  pub fn reset_goal_overall_funded(&mut self) {
    self.goal_overall_funded = None;
  }

  pub fn set_goal_overall_left(&mut self, goal_overall_left: i64) {
    self.goal_overall_left = Some(goal_overall_left);
  }

  pub fn with_goal_overall_left(mut self, goal_overall_left: i64) -> Category {
    self.goal_overall_left = Some(goal_overall_left);
    self
  }

  pub fn goal_overall_left(&self) -> Option<&i64> {
    self.goal_overall_left.as_ref()
  }

  pub fn reset_goal_overall_left(&mut self) {
    self.goal_overall_left = None;
  }

  pub fn set_deleted(&mut self, deleted: bool) {
    self.deleted = deleted;
  }

  pub fn with_deleted(mut self, deleted: bool) -> Category {
    self.deleted = deleted;
    self
  }

  pub fn deleted(&self) -> &bool {
    &self.deleted
  }


}



