/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MonthSummariesResponseData {
  #[serde(rename = "months")]
  months: Vec<::models::MonthSummary>,
  /// The knowledge of the server
  #[serde(rename = "server_knowledge")]
  server_knowledge: i64
}

impl MonthSummariesResponseData {
  pub fn new(months: Vec<::models::MonthSummary>, server_knowledge: i64) -> MonthSummariesResponseData {
    MonthSummariesResponseData {
      months: months,
      server_knowledge: server_knowledge
    }
  }

  pub fn set_months(&mut self, months: Vec<::models::MonthSummary>) {
    self.months = months;
  }

  pub fn with_months(mut self, months: Vec<::models::MonthSummary>) -> MonthSummariesResponseData {
    self.months = months;
    self
  }

  pub fn months(&self) -> &Vec<::models::MonthSummary> {
    &self.months
  }


  pub fn set_server_knowledge(&mut self, server_knowledge: i64) {
    self.server_knowledge = server_knowledge;
  }

  pub fn with_server_knowledge(mut self, server_knowledge: i64) -> MonthSummariesResponseData {
    self.server_knowledge = server_knowledge;
    self
  }

  pub fn server_knowledge(&self) -> &i64 {
    &self.server_knowledge
  }


}



