/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SaveCategoryResponseData {
  #[serde(rename = "category")]
  category: ::models::Category,
  /// The knowledge of the server
  #[serde(rename = "server_knowledge")]
  server_knowledge: i64
}

impl SaveCategoryResponseData {
  pub fn new(category: ::models::Category, server_knowledge: i64) -> SaveCategoryResponseData {
    SaveCategoryResponseData {
      category: category,
      server_knowledge: server_knowledge
    }
  }

  pub fn set_category(&mut self, category: ::models::Category) {
    self.category = category;
  }

  pub fn with_category(mut self, category: ::models::Category) -> SaveCategoryResponseData {
    self.category = category;
    self
  }

  pub fn category(&self) -> &::models::Category {
    &self.category
  }


  pub fn set_server_knowledge(&mut self, server_knowledge: i64) {
    self.server_knowledge = server_knowledge;
  }

  pub fn with_server_knowledge(mut self, server_knowledge: i64) -> SaveCategoryResponseData {
    self.server_knowledge = server_knowledge;
    self
  }

  pub fn server_knowledge(&self) -> &i64 {
    &self.server_knowledge
  }


}



