/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ScheduledTransactionsResponseData {
  #[serde(rename = "scheduled_transactions")]
  scheduled_transactions: Vec<::models::ScheduledTransactionDetail>,
  /// The knowledge of the server
  #[serde(rename = "server_knowledge")]
  server_knowledge: i64
}

impl ScheduledTransactionsResponseData {
  pub fn new(scheduled_transactions: Vec<::models::ScheduledTransactionDetail>, server_knowledge: i64) -> ScheduledTransactionsResponseData {
    ScheduledTransactionsResponseData {
      scheduled_transactions: scheduled_transactions,
      server_knowledge: server_knowledge
    }
  }

  pub fn set_scheduled_transactions(&mut self, scheduled_transactions: Vec<::models::ScheduledTransactionDetail>) {
    self.scheduled_transactions = scheduled_transactions;
  }

  pub fn with_scheduled_transactions(mut self, scheduled_transactions: Vec<::models::ScheduledTransactionDetail>) -> ScheduledTransactionsResponseData {
    self.scheduled_transactions = scheduled_transactions;
    self
  }

  pub fn scheduled_transactions(&self) -> &Vec<::models::ScheduledTransactionDetail> {
    &self.scheduled_transactions
  }


  pub fn set_server_knowledge(&mut self, server_knowledge: i64) {
    self.server_knowledge = server_knowledge;
  }

  pub fn with_server_knowledge(mut self, server_knowledge: i64) -> ScheduledTransactionsResponseData {
    self.server_knowledge = server_knowledge;
    self
  }

  pub fn server_knowledge(&self) -> &i64 {
    &self.server_knowledge
  }


}



