/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionsImportResponseData {
  /// The list of transaction ids that were imported.
  #[serde(rename = "transaction_ids")]
  transaction_ids: Vec<String>
}

impl TransactionsImportResponseData {
  pub fn new(transaction_ids: Vec<String>) -> TransactionsImportResponseData {
    TransactionsImportResponseData {
      transaction_ids: transaction_ids
    }
  }

  pub fn set_transaction_ids(&mut self, transaction_ids: Vec<String>) {
    self.transaction_ids = transaction_ids;
  }

  pub fn with_transaction_ids(mut self, transaction_ids: Vec<String>) -> TransactionsImportResponseData {
    self.transaction_ids = transaction_ids;
    self
  }

  pub fn transaction_ids(&self) -> &Vec<String> {
    &self.transaction_ids
  }


}



